### ISSUE TITLE
Remove old poetry lock from Meta.yaml

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/conda-lock-feedstock#30]
https://github.com/conda-forge/conda-lock-feedstock/blob/e6234425051a99bf6e25ae33ae12500352f42c9c/recipe/meta.yaml#L37

https://github.com/conda-incubator/conda-lock/blob/2a9b85aa9d2a5a1c55afae030fb8c0904f2b7b95/requirements.txt#L9

**Comment by rxm7706** [comment]
Created PR
https://github.com/conda-forge/conda-lock-feedstock/pull/31

**Comment by bollwyvl** [comment]
Please feel free to re-open if there are additional concerns about poetry.
